sequenceDiagram
ユーザ->>日程調整サービス: Google Calendarと連携
ユーザ->>Google認可サーバ: 認可やりとり.. 
Google認可サーバ-->>ユーザ: アクセストークン
ユーザ->>日程調整サービス: redirect
日程調整サービス->>Googleリソースサーバー: リソースアクセス
Googleリソースサーバー-->>日程調整サービス: レスポンス
