sequenceDiagram
ユーザ->>日程調整サービス: Google Calendarと連携
ユーザ->>Google認可サーバ: 認可やりとり.. 
Google認可サーバ-->>ユーザ: 認可コード
ユーザ->>日程調整サービス: redirect
日程調整サービス->>Google認可サーバ: トークンリクエスト
Google認可サーバ-->>日程調整サービス: アクセストークン
日程調整サービス->>Googleリソースサーバー: リソースアクセス
Googleリソースサーバー-->>日程調整サービス: レスポンス
