name: Create an issue for jibun release note

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "10 * * * *"

jobs:
  build:
    name: Create an issue for jibun release note
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
