on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "* * * * *"
name: Create an issue for jibun release note
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
