name: create issue

on:
  schedule:
    # 執筆に余裕を持ちたいので 27 日で設定
    - cron: "0 0 27 * *"

jobs:
  build:
    name: create issue
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
