name: Run Algolia script
on:
  push:
    branches:
      - main
    paths:
      - 'contents/posts/**'

jobs:
  build:
    name: algolia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Create .env
        run: |
          touch .env
          echo ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }} >> .env
          echo ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }} >> .env
      - name: npm install
        run: npm install
      - name: Run algolia script
        run: npm run build:algolia
      - name: Commin and push
        run: |
          git config --global user.name 'Kenzo Tanaka'
          git config --global user.email 'kenzo-tanaka@users.noreply.github.com'
          git add .
          git commit --allow-empty -m 'Run algolia'
          git push

